import clases

person1 = clases.Person()
person1.setName("Alexis")
person1.setLastName("Rodríguez")
person1.setAge(33)
person1.setHeight(1.70)
print("Datos de persona 1.")
print(f"Nombre: {person1.getName()}")
print(f"Apellidos: {person1.getLastName()}")
print(f"Altura: {person1.getHeight()}")
print(f"Edad: {person1.getAge()}")
print(person1.talk())
print(person1.sleep())

informatico = clases.Informatico()
informatico.setName("Arturo")
informatico.setLastName("Solís")
informatico.setAge(22)
informatico.setHeight(1.52)
print("\nDatos de informático.")
print(f"Nombre: {informatico.getName()}")
print(f"Apellido: {informatico.getLastName()}")
print(f"Altura: {informatico.getHeight()}")
print(f"Edad: {informatico.getAge()}")
print("---------- Actividades del informático ----------")
print(f"Lenguajes de programación: {informatico.getLanguages()}")
print(f"Actividad: {informatico.program()}")
new_language = "RUBY"
informatico.learnLanguages(new_language)
print(f"Lenguajes de programación: {informatico.getLanguages()}")
print(f"Actividad: {informatico.fixComputer()}")

print("\nDatos de técnico de redes.")
networ_technician = clases.NetworkTechnician()
networ_technician.setName("Alexis")
print(networ_technician.getName())
print("---------- Actividades del técnico de redes ----------")
print(networ_technician.networkAudit())
print(f"Lenguages heredados de la clase informático: {networ_technician.getLanguages()}")